print("Время отхода ко сну")
x = int(input("Колличество минут "))
y = x / 60
a = int(y)
b = round((y - a) * 60)
c = int(input("Часов "))
d = int(input("Минут "))
print("установить будильник на: ")
print("Часов ", a + c)
print("Минут ", b + d)